// Wave-B parity vectors — the launch-day proof the changelog referenced but never shipped.
// Each vector is scored by BOTH the real SQL standings() and the real JS scoreFor().
// Ladder: KO advance R32=4 R16=5 QF=6 SF=8 third=6 final=10 · bonus R32=4 R16=5 QF=6 SF=7 third=5 final=8
// armband ×2 on (advance+bonus) for qf/sf/fin only · upset flat +2 (never doubled) · champion +25 (never doubled)
// streak: 2→+5 3→+15 4+→+20 each · shield forgives first kn>=25 break after an exact, once.
// Placeholder ranks used here (France 3, Morocco 11, Brazil 5, Argentina 2, Norway 29, ...) — mechanics are rank-order-agnostic.
export const VECTORS = [
  { name:"01 r32 winner-only", kteams:{k1:{h:"South Africa",a:"Canada"}}, results:{k1:{w:"Canada",h:0,a:1}},
    player:{predictions:{k1:{w:"Canada",h:0,a:0}}}, expect:{pts:4,exact:0,correct:1} },
  { name:"02 r32 exact", kteams:{k1:{h:"South Africa",a:"Canada"}}, results:{k1:{w:"Canada",h:0,a:1}},
    player:{predictions:{k1:{w:"Canada",h:0,a:1}}}, expect:{pts:8,exact:1,correct:1} },
  { name:"03 qf exact no-chip", kteams:{k25:{h:"France",a:"Morocco"}}, results:{k25:{w:"France",h:2,a:1}},
    player:{predictions:{k25:{w:"France",h:2,a:1}}}, expect:{pts:12,exact:1,correct:1} },
  { name:"04 qf exact + armband", kteams:{k25:{h:"France",a:"Morocco"}}, results:{k25:{w:"France",h:2,a:1}},
    player:{predictions:{k25:{w:"France",h:2,a:1}}, chips:{qf:"k25"}}, expect:{pts:24,exact:1,correct:1} },
  { name:"05 armband on a miss = 0 (never creates)", kteams:{k25:{h:"France",a:"Morocco"}}, results:{k25:{w:"France",h:2,a:1}},
    player:{predictions:{k25:{w:"Morocco",h:0,a:1}}, chips:{qf:"k25"}}, expect:{pts:0,exact:0,correct:0} },
  { name:"06 qf winner-only + armband", kteams:{k25:{h:"France",a:"Morocco"}}, results:{k25:{w:"France",h:2,a:1}},
    player:{predictions:{k25:{w:"France",h:0,a:0}}, chips:{qf:"k25"}}, expect:{pts:12,exact:0,correct:1} },
  { name:"07 qf upset no-chip (+2)", kteams:{k25:{h:"France",a:"Morocco"}}, results:{k25:{w:"Morocco",h:1,a:0}},
    player:{predictions:{k25:{w:"Morocco",h:1,a:0}}}, expect:{pts:14,exact:1,correct:1} },
  { name:"08 qf upset + armband (upset NOT doubled)", kteams:{k25:{h:"France",a:"Morocco"}}, results:{k25:{w:"Morocco",h:1,a:0}},
    player:{predictions:{k25:{w:"Morocco",h:1,a:0}}, chips:{qf:"k25"}}, expect:{pts:26,exact:1,correct:1} },
  { name:"09 qf upset winner-only", kteams:{k25:{h:"France",a:"Morocco"}}, results:{k25:{w:"Morocco",h:1,a:0}},
    player:{predictions:{k25:{w:"Morocco",h:3,a:3}}}, expect:{pts:8,exact:0,correct:1} },
  { name:"10 qf favorite = no upset", kteams:{k25:{h:"France",a:"Morocco"}}, results:{k25:{w:"France",h:1,a:0}},
    player:{predictions:{k25:{w:"France",h:1,a:0}}}, expect:{pts:12,exact:1,correct:1} },
  { name:"11 streak 2-in-a-row (+5)", kteams:{k17:{h:"Canada",a:"Morocco"},k18:{h:"Paraguay",a:"France"}},
    results:{k17:{w:"Canada",h:1,a:0},k18:{w:"France",h:2,a:0}},
    player:{predictions:{k17:{w:"Canada",h:1,a:0},k18:{w:"France",h:2,a:0}}}, expect:{pts:25,exact:2,correct:2} },
  { name:"12 streak 3-in-a-row (+15)", kteams:{k17:{h:"Canada",a:"Morocco"},k18:{h:"Paraguay",a:"France"},k19:{h:"Brazil",a:"Norway"}},
    results:{k17:{w:"Canada",h:1,a:0},k18:{w:"France",h:2,a:0},k19:{w:"Norway",h:1,a:2}},
    player:{predictions:{k17:{w:"Canada",h:1,a:0},k18:{w:"France",h:2,a:0},k19:{w:"Norway",h:1,a:2}}}, expect:{pts:50,exact:3,correct:3} },
  { name:"13 streak 4-in-a-row (+40)", kteams:{k17:{h:"Canada",a:"Morocco"},k18:{h:"Paraguay",a:"France"},k19:{h:"Brazil",a:"Norway"},k20:{h:"Mexico",a:"England"}},
    results:{k17:{w:"Canada",h:1,a:0},k18:{w:"France",h:2,a:0},k19:{w:"Norway",h:1,a:2},k20:{w:"England",h:0,a:3}},
    player:{predictions:{k17:{w:"Canada",h:1,a:0},k18:{w:"France",h:2,a:0},k19:{w:"Norway",h:1,a:2},k20:{w:"England",h:0,a:3}}}, expect:{pts:80,exact:4,correct:4} },
  { name:"14 streak reset by a miss", kteams:{k17:{h:"Canada",a:"Morocco"},k18:{h:"Paraguay",a:"France"},k19:{h:"Brazil",a:"Norway"}},
    results:{k17:{w:"Canada",h:1,a:0},k18:{w:"France",h:2,a:0},k19:{w:"Norway",h:1,a:2}},
    player:{predictions:{k17:{w:"Canada",h:1,a:0},k18:{w:"France",h:9,a:9},k19:{w:"Norway",h:1,a:2}}}, expect:{pts:25,exact:2,correct:3} },
  { name:"15 shield forgives the first break (+5)", kteams:{k25:{h:"France",a:"Morocco"},k26:{h:"Spain",a:"Portugal"},k27:{h:"England",a:"Germany"}},
    results:{k25:{w:"France",h:2,a:1},k26:{w:"Spain",h:1,a:0},k27:{w:"England",h:3,a:1}},
    player:{predictions:{k25:{w:"France",h:2,a:1},k26:{w:"Spain",h:9,a:9},k27:{w:"England",h:3,a:1}}}, expect:{pts:35,exact:2,correct:3} },
  { name:"16 shield once-only (second break resets)", kteams:{k25:{h:"France",a:"Morocco"},k26:{h:"Spain",a:"Portugal"},k27:{h:"England",a:"Germany"},k28:{h:"Netherlands",a:"Croatia"},k29:{h:"Belgium",a:"Colombia"}},
    results:{k25:{w:"France",h:2,a:1},k26:{w:"Spain",h:1,a:0},k27:{w:"England",h:3,a:1},k28:{w:"Netherlands",h:2,a:0},k29:{w:"Belgium",h:1,a:0}},
    player:{predictions:{k25:{w:"France",h:2,a:1},k26:{w:"Spain",h:9,a:9},k27:{w:"England",h:3,a:1},k28:{w:"Netherlands",h:9,a:9},k29:{w:"Belgium",h:1,a:0}}}, expect:{pts:56,exact:3,correct:5} },
  { name:"17 shield no-retro (miss before any exact)", kteams:{k25:{h:"France",a:"Morocco"},k26:{h:"Spain",a:"Portugal"}},
    results:{k25:{w:"France",h:2,a:1},k26:{w:"Spain",h:1,a:0}},
    player:{predictions:{k25:{w:"France",h:9,a:9},k26:{w:"Spain",h:1,a:0}}}, expect:{pts:18,exact:1,correct:2} },
  { name:"18 champion +25 (never doubled)", kteams:{k25:{h:"France",a:"Morocco"}}, results:{k25:{w:"France",h:1,a:0},_champ:"Argentina"},
    player:{predictions:{k25:{w:"France",h:1,a:0}}, champ:"Argentina"}, expect:{pts:37,exact:1,correct:1} },
  { name:"19 champion wrong = 0", kteams:{k25:{h:"France",a:"Morocco"}}, results:{k25:{w:"France",h:1,a:0},_champ:"Argentina"},
    player:{predictions:{k25:{w:"France",h:1,a:0}}, champ:"Brazil"}, expect:{pts:12,exact:1,correct:1} },
  { name:"20 FINAL armband big swing (+36)", kteams:{k32:{h:"Argentina",a:"France"}}, results:{k32:{w:"Argentina",h:2,a:1}},
    player:{predictions:{k32:{w:"Argentina",h:2,a:1}}, chips:{fin:"k32"}}, expect:{pts:36,exact:1,correct:1} },
  { name:"21 group outcome+exact regression", kteams:{}, results:{m1:{h:2,a:0}},
    player:{predictions:{m1:{o:"H",h:2,a:0}}}, expect:{pts:5,exact:1,correct:1} },
  { name:"22 mixed group+KO base (no chips = today's math)", kteams:{k1:{h:"South Africa",a:"Canada"}}, results:{m1:{h:2,a:0},m2:{h:1,a:1},k1:{w:"Canada",h:0,a:1}},
    player:{predictions:{m1:{o:"H",h:2,a:0},m2:{o:"D",h:1,a:1},k1:{w:"Canada",h:0,a:1}}}, expect:{pts:18,exact:3,correct:3} },
  { name:"23 k31 third: upset yes, armband impossible", kteams:{k31:{h:"Brazil",a:"Norway"}}, results:{k31:{w:"Norway",h:1,a:0}},
    player:{predictions:{k31:{w:"Norway",h:1,a:0}}, chips:{fin:"k31"}}, expect:{pts:13,exact:1,correct:1} },
  { name:"24 settled tie, no prediction = 0", kteams:{k25:{h:"France",a:"Morocco"}}, results:{k25:{w:"France",h:1,a:0}},
    player:{predictions:{}}, expect:{pts:0,exact:0,correct:0} },
  // ---- flag OFF (wc:powerups_live unset): server + client gate must yield the pure base ladder ----
  { name:"25 flag OFF: armband ignored", flagOff:true, kteams:{k25:{h:"France",a:"Morocco"}}, results:{k25:{w:"France",h:2,a:1}},
    player:{predictions:{k25:{w:"France",h:2,a:1}}, chips:{qf:"k25"}}, expect:{pts:12,exact:1,correct:1} },
  { name:"26 flag OFF: upset ignored", flagOff:true, kteams:{k25:{h:"France",a:"Morocco"}}, results:{k25:{w:"Morocco",h:1,a:0}},
    player:{predictions:{k25:{w:"Morocco",h:1,a:0}}}, expect:{pts:12,exact:1,correct:1} },
  { name:"27 flag OFF: shield does not forgive", flagOff:true, kteams:{k25:{h:"France",a:"Morocco"},k26:{h:"Spain",a:"Portugal"},k27:{h:"England",a:"Germany"}},
    results:{k25:{w:"France",h:2,a:1},k26:{w:"Spain",h:1,a:0},k27:{w:"England",h:3,a:1}},
    player:{predictions:{k25:{w:"France",h:2,a:1},k26:{w:"Spain",h:9,a:9},k27:{w:"England",h:3,a:1}}}, expect:{pts:30,exact:2,correct:3} },
];
